<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Fonts -->
    <link href="https://fonts.googleapis.com/css2?family=Nunito:wght@400;600;700&display=swap" rel="stylesheet">

    <!-- Styles -->
    <link rel="stylesheet" href="{{ asset('css/app.css') }}">

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.6.1/font/bootstrap-icons.css">


    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>

    <script src='https://api.mapbox.com/mapbox-gl-js/v2.9.2/mapbox-gl.js'></script>
    <link href='https://api.mapbox.com/mapbox-gl-js/v2.9.2/mapbox-gl.css' rel='stylesheet' />

    <script src='https://api.mapbox.com/mapbox-gl-js/plugins/mapbox-gl-geocoder/v4.7.0/mapbox-gl-geocoder.min.js'></script>
    <link rel='stylesheet' href='https://api.mapbox.com/mapbox-gl-js/plugins/mapbox-gl-geocoder/v4.7.0/mapbox-gl-geocoder.css' type='text/css' />

    <style>
      body {
        margin: 0;
        padding: 0;
      }

      #map-container {
        position: relative;
        height: 450px;
        margin-bottom: 27px;
    }

    #map {
        position: relative;
        height: inherit;
        width: inherit;
    }
    </style>

    <style>
    @media (min-width: 768px)
{
    
}


/* Extra small devices (phones, 600px and down) */
@media only screen and (max-width: 600px) {
    #main-div {
        top: 35%;
        width: 100%;
        left: 0%;
        position: absolute;
        }

#body{
    background-size: 101% 36% !important;
}
}

@media (min-width: 640px)
{
    #main-div {
        top: 15%;
        left: 23%;
        position: absolute;
    /* width: 100%; */
    }
}

/* Small devices (portrait tablets and large phones, 600px and up) */
/* @media only screen and (min-width: 600px) {...} */

/* Medium devices (landscape tablets, 768px and up) */
@media only screen and (min-width: 768px) {
    #main-div {
        /* top: 20%;
    width: 50%;
    left: 10%; */

    /* top: 15%;
    width: 38%;
    left: 57%; */
}

#body{
    background-size: 101% 100% !important;
    /* background-size: 100% 64%; */
}}

/* Large devices (laptops/desktops, 992px and up) */
/* @media only screen and (min-width: 992px) {...} */

/* Extra large devices (large laptops and desktops, 1200px and up) */
/* @media only screen and (min-width: 1200px) {...} */

[x-cloak] { display: none !important; }

html {
  scroll-behavior: smooth;
}

.container {
  overflow-x: scroll;
  scroll-behavior: smooth;
}


</style>

<style>
    .swing-in-right-bck {
	-webkit-animation: swing-in-right-bck 0.6s cubic-bezier(0.175, 0.885, 0.320, 1.275) 1s both;
	        animation: swing-in-right-bck 0.6s cubic-bezier(0.175, 0.885, 0.320, 1.275) 1s both;
}

.swing-in-left-fwd {
	-webkit-animation: swing-in-left-fwd 0.9s cubic-bezier(0.175, 0.885, 0.320, 1.275) both;
	        animation: swing-in-left-fwd 0.9s cubic-bezier(0.175, 0.885, 0.320, 1.275) both;
}

.swing-out-right-fwd {
	-webkit-animation: swing-out-right-fwd 0.55s cubic-bezier(0.600, -0.280, 0.735, 0.045) both;
	        animation: swing-out-right-fwd 0.55s cubic-bezier(0.600, -0.280, 0.735, 0.045) both;
}

/* ----------------------------------------------
 * Generated by Animista on 2022-10-2 23:41:46
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info. 
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

/**
 * ----------------------------------------
 * animation swing-in-right-bck
 * ----------------------------------------
 */
@-webkit-keyframes swing-in-right-bck {
  0% {
    -webkit-transform: rotateY(70deg);
            transform: rotateY(70deg);
    -webkit-transform-origin: right;
            transform-origin: right;
    opacity: 0;
  }
  100% {
    -webkit-transform: rotateY(0);
            transform: rotateY(0);
    -webkit-transform-origin: right;
            transform-origin: right;
    opacity: 1;
  }
}
@keyframes swing-in-right-bck {
  0% {
    -webkit-transform: rotateY(70deg);
            transform: rotateY(70deg);
    -webkit-transform-origin: right;
            transform-origin: right;
    opacity: 0;
  }
  100% {
    -webkit-transform: rotateY(0);
            transform: rotateY(0);
    -webkit-transform-origin: right;
            transform-origin: right;
    opacity: 1;
  }
}

/* ----------------------------------------------
 * Generated by Animista on 2022-10-14 23:54:55
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info. 
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

/**
 * ----------------------------------------
 * animation swing-in-left-fwd
 * ----------------------------------------
 */
@-webkit-keyframes swing-in-left-fwd {
  0% {
    -webkit-transform: rotateY(100deg);
            transform: rotateY(100deg);
    -webkit-transform-origin: left;
            transform-origin: left;
    opacity: 0;
  }
  100% {
    -webkit-transform: rotateY(0);
            transform: rotateY(0);
    -webkit-transform-origin: left;
            transform-origin: left;
    opacity: 1;
  }
}
@keyframes swing-in-left-fwd {
  0% {
    -webkit-transform: rotateY(100deg);
            transform: rotateY(100deg);
    -webkit-transform-origin: left;
            transform-origin: left;
    opacity: 0;
  }
  100% {
    -webkit-transform: rotateY(0);
            transform: rotateY(0);
    -webkit-transform-origin: left;
            transform-origin: left;
    opacity: 1;
  }
}

/* ----------------------------------------------
 * Generated by Animista on 2022-10-14 23:57:9
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info. 
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

/**
 * ----------------------------------------
 * animation swing-out-right-fwd
 * ----------------------------------------
 */
@-webkit-keyframes swing-out-right-fwd {
  0% {
    -webkit-transform: rotateY(0);
            transform: rotateY(0);
    -webkit-transform-origin: right;
            transform-origin: right;
    opacity: 1;
  }
  100% {
    -webkit-transform: rotateY(70deg);
            transform: rotateY(70deg);
    -webkit-transform-origin: right;
            transform-origin: right;
    opacity: 0;
  }
}
@keyframes swing-out-right-fwd {
  0% {
    -webkit-transform: rotateY(0);
            transform: rotateY(0);
    -webkit-transform-origin: right;
            transform-origin: right;
    opacity: 1;
  }
  100% {
    -webkit-transform: rotateY(70deg);
            transform: rotateY(70deg);
    -webkit-transform-origin: right;
            transform-origin: right;
    opacity: 0;
  }
}


</style>



    @livewireStyles
</head>

<body  x-cloak x-data="{ overlay: false }" id="body" class="bg-white font-family-karla flex flex-col scroll-smooth" style="background-repeat: no-repeat; height:20rem; background-image: url('{{ asset($header_image ?? '') }}'); background-attachment: fixed; background-size: 100% 40%;">
    @include('partials.nav')
    <div :class="overlay ? 'z-50 absolute w-full h-full bg-black opacity-50' : ''" class="overlay" style="z-index: 5; height:150%"></div>
    <div class="w-full bg-cover bg-center bg-fixed">
        
    </div>

        <main class="absolute bg-white rounded-2xl w-full lg:w-1/2 sm:w-full shadow-2xl" id="main-div">
            @yield('content')
        </main>

    @livewireScripts

    <script src="//cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    <script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>
    <x-livewire-alert::scripts />

    <script src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.13.0/js/all.min.js"
    integrity="sha256-KzZiKy0DWYsnwMF+X1DvQngQ2/FxF7MF3Ff72XcpuPs=" crossorigin="anonymous"></script>
    <script src="https://js.pusher.com/7.0/pusher.min.js"></script>
    <script src="https://js.pusher.com/beams/1.0/push-notifications-cdn.js"></script>
    
    <script>

        // Enable pusher logging - don't include this in production
        Pusher.logToConsole = true;

        var pusher = new Pusher('564c6570a0c13950eb56', {
        cluster: 'ap2'
        });

        var channel = pusher.subscribe('test-channel');
                channel.bind('myEvent', function(data) {
        });


        

        

        document.addEventListener("DOMContentLoaded", function(event) {
            // Your code to run since DOM is loaded and ready

        window.addEventListener('orderUpdate', event => { 
            var orderChannel = pusher.subscribe(`orderUpdated_${event.detail.order}`);

            orderChannel.bind('order-updated', function (data) {
                
            window.livewire.emit('orderUpdated', data.order.status);
                
            });

        })

        window.addEventListener('driverUpdate', event => {
                var driverChannel = pusher.subscribe(`driverLocationUpdated_${event.detail.order}`);

                driverChannel.bind('driverLocation', function (data) {
                        updateOrder();
                });

        })

        function updateOrder() {
                window.livewire.emit('orderUpdated');    
        }
        
        const beamsClient = new PusherPushNotifications.Client({
            instanceId: {{env('BEAM_instanceId')}}
        });

        beamsClient.getRegistrationState()
        .then(state => {
        let states = PusherPushNotifications.RegistrationState
        switch(state) {
        case states.PERMISSION_DENIED: {
                NewUserNewUser
                break
        }
        case states.PERMISSION_GRANTED_REGISTERED_WITH_BEAMS: {
                beamsClient.start()
            .then(() => beamsClient.addDeviceInterest('{{config('app.name')}}_{{ auth()->user()->last_name }}_{{ auth()->user()->id }}'))
            .then(() => console.log('Successfully registered and subscribed!'))
            .catch(console.error);
            break
        }
        case states.PERMISSION_GRANTED_NOT_REGISTERED_WITH_BEAMS:{
                beamsClient.start()
            .then(() => beamsClient.addDeviceInterest('{{config('app.name')}}_{{ auth()->user()->last_name }}_{{ auth()->user()->id }}'))
            .then(() => console.log('Successfully registered and subscribed!'))
            .catch(console.error);
          break
        }
        case states.PERMISSION_PROMPT_REQUIRED: {
                swal({
                title: "Notification required!",
                text: "Please enable notifications to recieve order updates.",
                icon: "info",
                });
                beamsClient.start()
            .then(() => beamsClient.addDeviceInterest('{{config('app.name')}}_{{ auth()->user()->last_name }}_{{ auth()->user()->id }}'))
            .then(() => console.log('Successfully registered and subscribed!'))
            .catch(console.error);
          break
        }
      }
    })
      .catch(console.error)

        });

    </script>



</body>

</html>